nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/xingzhang-suse/security-ui-exts/gh-pages/extensions/sbombastic-image-vulnerability-scanner/0.2.1-private
  compressedEndpoint: >-
    https://raw.githubusercontent.com/xingzhang-suse/security-ui-exts/gh-pages/extensions/sbombastic-image-vulnerability-scanner/0.2.1-private.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.10.0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
