name: Adds all issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        env:
          APP_ID: ${{ secrets.ADD_ISSUE_APP_ID }}
          PRIVATE_KEY: ${{ secrets.ADD_ISSUE_PRIVATE_KEY }}
        if: env.APP_ID != '' && env.PRIVATE_KEY != ''
        with:
          client-id: ${{ secrets.ADD_ISSUE_APP_ID }}
          private-key: ${{ secrets.ADD_ISSUE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-organization-projects: write
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        if: steps.app-token.outcome == 'success'
        with:
          project-url: https://github.com/orgs/rancher/projects/143
          github-token: ${{ steps.app-token.outputs.token }}
